### ISSUE TITLE
AWS max limit

### ISSUE THREAD

**Issue by itmwiw** [redhat-cop/egressip-ipam-operator#75] opened 2021-07-02 09:26 UTC
Hello,
Is there a way to prevent egress Ips from being created on netnamespaces when the aws secondary Ip addresses limit is reached. 
Right now, the egress Ips are created on the nernamespaces no matter what. Only hostsubnet are affected by AWS response. So when the AWS limit is reached, the egress Ips are created on the netnamesapces but not on the hostsubnet which causes the traffic to be dropped.
At least that's what I think happens. I would appreciate if you confirm, or refute, my analysis. And if this is the right description of what happen help me fix this (for exemple showing the portion of code I could change to have the least impact possible)
Thanks in advance.

**Comment by raffaelespazzoli** [comment] 2021-07-02 12:05
the behavior you describe is correct and by design. The egreesIP to namespace assignment is conceptually separated from the egressIP to node assignment phase. This is needed for two reasons:
1. to prevent namespace-assigned egressIP shuffling. Once an egressIP is assigned to a namespace the expectation is that the namespace tenant will use it to create firewall rules and possibly other configurations, so we cannot change it.
2. to allow for manual assignment of egreesIPs to namespaces.

If you run out of secondary IPs in a AWS instance the only fix known today is to change instance type (pick one that can house more secondary  IPs https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI ) or add more nodes. It is recommended to use homogeneous nodes as the operator at this point will simply assign secondary IPs in a round robin fashion not taking into account potential different secondary IP capacities deriving from using different instance types.

**Closed** 2021-09-29 13:07 UTC
